#!/bin/bash

## Force 'C' locale for package build to avoid R encoding 'bugs'.
export LC_ALL=C

build="FALSE"
check="FALSE"
binary="FALSE"
install="FALSE"

while getopts "bczi" optname
  do
    case "$optname" in
      "b")
        build="TRUE"
        ;;
      "c")
        check="TRUE"
        ;;
      "z")
        binary="TRUE"
        ;;
      "i")
        install="TRUE"
        ;;
      "?")
        echo "Unknown option $OPTARG"
        ;;
      *)
      # Should not occur
        echo "Unknown error while processing options"
        ;;
    esac
  done

shift $(($OPTIND - 1))
pack=$1

if [[ $pack == "" ]] ; then
    cat <<EOF
Usage: build-package [-bczi] <package>

Options:
 -b : Build package
 -c : Run R CMD check on package
 -z : Build a binary version of package
 -i : Install package
EOF
    exit -1
else
    
    rargs="pack<-'$pack'
build<-$build
check<-$check
binary<-$binary
install<-$install
source('src/make/make.R')"

Rscript - <<EOF
pack <- "$pack"
build <- $build
check <- $check
binary <- $binary
install <- $install
source("src/make/make.R")
EOF
fi
