#!/bin/bash

## Force 'C' locale for package build to avoid R encoding 'bugs'.
export LC_ALL=C
pack=$1
regexp=$2

echo "================================================================================"
echo " BUILD"
echo "--------------------------------------------------------------------------------"
Rscript -e "pack<-'$pack'; check <- FALSE; source('src/make/make.R')"

echo "================================================================================"
echo " INSTALL"
echo "--------------------------------------------------------------------------------"
R CMD INSTALL pkg/$pack

echo "================================================================================"
echo " EXTERNAL TEST"
echo "--------------------------------------------------------------------------------"
Rscript -e "use.package=TRUE; pack<-'$pack'; runit.regexp='$regexp'; source('src/runit/testsuite.R')"
