#!/bin/bash

./build-package -i mlr > logs/build_mlr.log 2>&1
./build-package -i mlrTune > logs/build_mlrTune.log 2>&1
./build-package -i mlrVarsel > logs/build_mlrVarsel.log 2>&1
./build-package -i mlrChains > logs/build_mlrChains.log 2>&1
./build-package -i mlrBenchmark > logs/build_mlrBenchmark.log 2>&1

./test-package mlr > logs/test_mlr.log 2>&1
./test-package mlrTune > logs/test_mlrTune.log 2>&1
./test-package mlrVarsel > logs/test_mlrVarsel.log 2>&1
./test-package mlrChains > logs/test_mlrChains.log 2>&1
./test-package mlrBenchmark > logs/test_mlrBenchmark.log 2>&1

R CMD check pkg/mlr > logs/check_mlr.log 2>&1
R CMD check pkg/mlrTune > logs/check_mlrTune.log 2>&1
R CMD check pkg/mlrVarsel > logs/check_mlrVarsel.log 2>&1
R CMD check pkg/mlrChains > logs/check_mlrChains.log 2>&1
R CMD check pkg/mlrBenchmark > logs/check_mlrBenchmark.log 2>&1

cat logs/build_*.log | grep "building" > logs/summary.txt
cat logs/test_mlr.log | grep "mlr - " >> logs/summary.txt
cat logs/test_mlrTune.log | grep "mlrTune - " >> logs/summary.txt
cat logs/test_mlrVarsel.log | grep "mlrVarsel - " >> logs/summary.txt
cat logs/test_mlrChains.log | grep "mlrChains - " >> logs/summary.txt
cat logs/test_mlrBenchmark.log | grep "mlrBenchmark - " >> logs/summary.txt

mutt -s "[mlr packs: build-test-check]" bernd_bischl@gmx.net < logs/summary.txt 
