#' @include resample.instance.r
#' @include bs.desc.r
roxygen()


#' A bs.instance object is mainly a set of integer vectors generated by bootstrapping. 
#' They indicate the training part of data for different instances of bs.
#'
#' @note Normally you don't want to use the S4 constructor, but instead \code{\link{make.bs.instance}}.
#' 
#' @title bs.instance
#' @exportClass bs.instance

setClass(
		"bs.instance", 
		contains = c("resample.instance"))                                                     

#' Constructor.
#' @title bs.instance constructor

setMethod(
  f = "initialize",
  signature = signature("bs.instance"),
  def = function(.Object, desc, size) {
	inds <- boot(1:size, R=desc["iters"], function(data,inds) inds)$t
	inds <- as.list(as.data.frame(t(inds)))
	names(inds) <- NULL
	
	callNextMethod(.Object, desc=desc, size=size, inds=inds)
  }
)


