#' @include resample.instance.r
#' @include cv.desc.r
roxygen()


#' A cv.instance object is mainly a set of integer vectors generated by cross-validation. 
#' They indicate the training part of data for different instances of cv. 
#'
#' @note Normally you don't want to use the S4 constructor, but instead \code{\link{make.cv.instance}}.
#' 
#' @title cv.instance
#' @exportClass cv.instance

setClass(
		"cv.instance", 
		contains = c("resample.instance")
)                                                     

#' Constructor.
#' @title cv.instance constructor

setMethod(
  f = "initialize",
  signature = signature("cv.instance"),
  def = function(.Object, desc, size) {
    inds <- sample(1:size)
    # don't warn when we can't split evenly
    s <- suppressWarnings(split(1:size, 1:desc["iters"]))
    inds <- lapply(s, function(x) inds[-x])

	callNextMethod(.Object, desc=desc, size=size, inds=inds)
  }
)


setGeneric(
	name = "make.cv.instance",
	def = function(task, iters) {
		standardGeneric("make.cv.instance")
	}
)

#' \code{make.cv.instance} generates a \code{\linkS4class{cv.instance}} object, which encapsulates the generated indices of training and test sets.
#' 
#' @param size [integer] \cr Size of the data set to resample. 
#' @param iters [integer] \cr Number of generated subsets / resampling iterations.
#' 
#' @return A \code{\linkS4class{cv.instance}} object, which encapsulates the generated indices of training and test sets.
#' 
#' @export
#' @rdname make.cv.instance 
#' 
#' @usage make.cv.instance(size, iters)
#' 
#' @examples 
#' data(iris)
#' rin <- make.cv.instance(size=nrow(iris), iters=10)
#' 
#' @seealso \code{\link{resample.fit}}, \code{\linkS4class{cv.instance}}
#' @title make.cv.instance

setMethod(
		f = "make.cv.instance",
		signature = c(task="learn.task", iters="numeric"),
		def = function(task, iters) {
			desc <- new("cv.desc", iters=iters)
			return(new("cv.instance", desc=desc, size=task["size"]))
		}
)

