#' @include resample.instance.r
#' @include subsample.desc.r
roxygen()

#' A subsample.instance object is mainly a set of integer vectors generated by subsampling. 
#' They indicate the training part of data for different instances of subsample.
#'
#' @note Normally you don't want to use the S4 constructor, but instead \code{\link{make.res.instance}}.
#' 
#' @title subsample.instance
#' @exportClass subsample.instance

setClass(
		"subsample.instance", 
		contains = c("resample.instance")
)                                                     


#' Constructor.
#' @title subsample.instance constructor

setMethod(
		f = "initialize",
		signature = signature("subsample.instance"),
		def = function(.Object, desc, size) {
			if (missing(desc))
				return(.Object)
			inds <- lapply(1:desc["iters"], function(x) sample(1:size, size*desc["split"]))
			callNextMethod(.Object, desc=desc, size=size, inds=inds)
		}
)

