
test.task.desc <- function() {
	costs = matrix(1:4, 2, 2)
	rownames(costs) = colnames(costs) = c("M", "R") 
	ct = make.task(target="Class", binaryclass.df, id="mytask", costs=costs, 
			positive="M", exclude="V1")
	checkEquals(ct@id, "mytask")	
	checkEquals(ct["costs"], costs)	
	checkEquals(ct["positive"], "M")	
	checkEquals(ct["negative"], "R")

	ct = make.task(target="Species", multiclass.df, id="mytask2")
	checkEquals(ct@id, "mytask2")	
	checkEquals(dim(ct["costs"]), c(0,0))	
	checkTrue(is.na(ct["positive"]))
	checkTrue(is.na(ct["negative"]))
	
	rt = make.task(target="medv", regr.df, id="mytask3") 
	checkEquals(rt@id, "mytask3")	
	checkEquals(dim(rt["costs"]), c(0,0))	
	checkTrue(is.na(rt["positive"]))
	checkTrue(is.na(rt["negative"]))
  
  checkEquals(multiclass.task["size"], 150) 
  checkEquals(multiclass.task["dim"], 4)  
  checkEquals(multiclass.task["n.feat"]["double"], 4, checkNames=FALSE)  
  checkEquals(multiclass.task["n.feat"]["int"], 0, checkNames=FALSE)  
  checkEquals(multiclass.task["n.feat"]["fact"], 0, checkNames=FALSE)  
  checkEquals(multiclass.task["n.feat"]["log"], 0, checkNames=FALSE)  
  checkEquals(multiclass.task["n.feat"]["char"], 0, checkNames=FALSE)  
  checkEquals(multiclass.task["has.missing"], F)  
  checkEquals(multiclass.task["is.classif"], T) 
  checkEquals(multiclass.task["is.regr"], F)  
  checkEquals(multiclass.task["class.levels"], c("setosa", "versicolor", "virginica"))  
  checkEquals(multiclass.task["class.nr"], 3) 
  checkEquals(multiclass.task["class.dist"], c(setosa=50, versicolor=50, virginica=50)) 
  checkEquals(multiclass.task["is.binary"], F)
  
  # check missing values
  df = multiclass.df
  df[1,1] = as.numeric(NA)
  ct = make.task(target="Species", data=df)
  checkEquals(ct["has.missing"], T) 
  
  ct = make.task(target=binaryclass.target, data=binaryclass.df, exclude="V1")
  checkEquals(ct["size"], 208)  
  checkEquals(ct["dim"], 59)  
  checkEquals(ct["n.feat"]["double"], 59, checkNames=FALSE)  
  checkEquals(ct["n.feat"]["int"], 0, checkNames=FALSE)  
  checkEquals(ct["n.feat"]["fact"], 0, checkNames=FALSE)  
  checkEquals(ct["n.feat"]["log"], 0, checkNames=FALSE)  
  checkEquals(ct["n.feat"]["char"], 0, checkNames=FALSE)  
  checkEquals(ct["has.missing"], F) 
  checkEquals(ct["is.classif"], T)  
  checkEquals(ct["is.regr"], F) 
  checkEquals(ct["class.levels"], c("M", "R"))  
  checkEquals(ct["class.nr"], 2)  
  checkEquals(ct["class.dist"], c(M=111, R=97)) 
  checkEquals(ct["is.binary"], T) 
  
  checkEquals(regr.task["size"], 506) 
  checkEquals(regr.task["dim"], 13) 
  checkEquals(regr.task["n.feat"]["double"], 12, checkNames=FALSE)  
  checkEquals(regr.task["n.feat"]["int"], 0, checkNames=FALSE)  
  checkEquals(regr.task["n.feat"]["fact"], 1, checkNames=FALSE)  
  checkEquals(regr.task["n.feat"]["log"], 0, checkNames=FALSE)  
  checkEquals(regr.task["n.feat"]["char"], 0, checkNames=FALSE)  
  checkEquals(regr.task["has.missing"], F)  
  checkEquals(regr.task["is.classif"], F) 
  checkEquals(regr.task["is.regr"], T)  
  checkTrue(is.na(regr.task["class.levels"])) 
  checkTrue(is.na(regr.task["class.nr"])) 
  checkTrue(is.na(regr.task["class.dist"])) 
  checkTrue(is.na(regr.task["is.binary"]))  
  
}