test.LearnerParameter = function() {
  p = makeNumericVectorLearnerParameter("x", dim=2, lower=0, upper=2)
  checkEquals(p@id, "x")
  checkEquals(lower(p), c(0,0))
  checkEquals(upper(p), c(2,2))
  checkEquals(p@when, "train")
  checkTrue(!isFeasible(p, 1))
  checkTrue(isFeasible(p, c(1,1)))
  p = makeNumericVectorLearnerParameter("x", lower=0, upper=2)
  checkEquals(lower(p), 0)
  checkEquals(upper(p), 2)
  checkTrue(isFeasible(p, 1))
  checkTrue(isFeasible(p, c(1,1)))

  p = makeIntegerVectorLearnerParameter("x", dim=2, lower=0L, upper=2L)
  checkEquals(p@id, "x")
  checkEquals(lower(p), c(0,0))
  checkEquals(upper(p), c(2,2))
  checkEquals(p@when, "train")
  checkTrue(!isFeasible(p, 1))
  checkTrue(isFeasible(p, c(1,1)))
  p = makeIntegerVectorLearnerParameter("x", lower=0L, upper=2L)
  checkEquals(lower(p), 0)
  checkEquals(upper(p), 2)
  checkTrue(isFeasible(p, 1))
  checkTrue(isFeasible(p, c(1,1)))
}