pack.files = c(
  "mlrEDA/aaa.R",
#  "mlrEDA/bench.R",
  "mlrEDA/capLargeValues.R",
  "mlrEDA/summarizeData.R",
  "mlrEDA/summarizeColumns.R",
  "mlrEDA/summarizeLevels.R",
  "mlrEDA/summarizeDates.R",
  "mlrEDA/summarizeNA.R",
  "mlrEDA/convertColumnNames.R",
  "mlrEDA/convertColumns.R",
  "mlrEDA/convertDates.R",
  "mlrEDA/mergeFactorLevelsBySize.R",
#  "mlrEDA/makeMonomials.R",
  "mlrEDA/generateMDSResult.R",
  "mlrEDA/generatePCAResult.R",
  "mlrEDA/generateVarsel2dResult.R",
  "mlrEDA/plotFeatDistr.R",
  "mlrEDA/plotPCA.R",
  "mlrEDA/plotMDS.R",
  "mlrEDA/plot2d.R",
  "mlrEDA/varsel2d.R",
  "mlrEDA/writeEDAReport.R"
)