#!/usr/bin/env Rscript

library(staticdocs)
# see https://github.com/hadley/staticdocs/
library(BBmisc)
#FIXME 
#options(BBmisc.ProgressBar.style="off")

ddir = "html"
if(file.exists(ddir))
  unlink(ddir, recursive = TRUE)
build_package("pkg", base_path = ddir)
