allowed.rd.files <<- c( 		
		"data.desc-class.Rd",
			"initialize,data.desc-method.Rd",
#			"as.character,data.desc-method.Rd",
#			"print,data.desc-method.Rd",
#			"show,data.desc-method.Rd",
		"learn.task-class.Rd",
			"initialize,learn.task-method.Rd",
#			"print,learn.task-method.Rd",
#			"show,learn.task-method.Rd",
			"getter,learn.task-method.Rd",
			"set.train.par,learn.task-method.Rd",
			"set.predict.par,learn.task-method.Rd",
		"learner.props-class.Rd",
#			"print,learner.props-method.Rd",
#			"show,learner.props-method.Rd",
		"classif.task-class.Rd",
#			"as.character,classif.task-method.Rd",
			"initialize,classif.task-method.Rd",
			"initialize,regr.task-method.Rd",
			"getter,classif.task-method.Rd",
		"regr.task-class.Rd",
#			"as.character,regr.task-method.Rd",
		"make.classif.task.Rd",
		"make.regr.task.Rd",
		"train.Rd",
			"train.learner,wrapped.learner,formula,data.frame,numeric,list-method.Rd",
		"predict,learn.task-method.Rd",
			"predict,classif.task-method.Rd",
			"predict,regr.task-method.Rd",
		"predict.Rd",
		"performance.Rd",
		"conf.matrix.Rd",
				
		"resample.desc-class.Rd",
			"getter,resample.desc-method.Rd",
		"cv.desc-class.Rd",
			"initialize,cv.desc-method.Rd",
		"bs.desc-class.Rd",
			"initialize,bs.desc-method.Rd",
		"subsample.desc-class.Rd",
			"initialize,subsample.desc-method.Rd",
		"make.cv.desc.Rd",
		"make.bs.desc.Rd",
		
		"resample.instance-class.Rd",
			"initialize,resample.instance-method.Rd",
			"getter,resample.instance-method.Rd",
		"cv.instance-class.Rd",
			"initialize,cv.instance-method.Rd",
		"bs.instance-class.Rd",
			"initialize,bs.instance-method.Rd",
		"subsample.instance-class.Rd",
			"initialize,subsample.instance-method.Rd",
		"make.res.instance.Rd",
		"make.cv.instance.Rd",
		"make.bs.instance.Rd",
		"resample.result-class.Rd",
#			"as.character,resample.result-method.Rd",
#			"print,resample.result-method.Rd",
#			"show,resample.result-method.Rd",
			"getter,resample.result-method.Rd",
		
		"wrapped.learner.classif-class.Rd",
			"initialize,wrapped.learner.classif-method.Rd",
		"wrapped.learner.regr-class.Rd",
		"wrapped.learner-class.Rd",
			"initialize,wrapped.learner-method.Rd",
#			"as.character,wrapped.learner-method.Rd",
#			"print,wrapped.learner-method.Rd",
#			"show,wrapped.learner-method.Rd",
		"wrapped.model-class.Rd",
#			"as.character,wrapped.model-method.Rd",
#			"print,wrapped.model-method.Rd",
#			"show,wrapped.model-method.Rd",
			"getter,wrapped.model-method.Rd",
		"make.learner.Rd",
		"set.train.par.Rd",
		"set.predict.par.Rd",

		"resample.fit.Rd",
		"resample.performance.Rd",
		"tune.Rd",
		"combine.ranges.Rd",
		"grid.control.Rd",
		"ps.control.Rd",
		
		"bench.exp.Rd",
		"bench.add.Rd",
		
		"naiveBayes-class.Rd",
#			"initialize,naiveBayes-method.Rd",
		"kknn.classif-class.Rd",
#			"initialize,kknn.classif-method.Rd",
		"logreg-class.Rd",
#			"initialize,logreg-method.Rd",
		"nnet.multinom-class.Rd",
#			"initialize,nnet.multinom-method.Rd",
		"lda-class.Rd",
#			"initialize,lda-method.Rd",
		"qda-class.Rd",
#			"initialize,qda-method.Rd",
		"rda-class.Rd",
#			"initialize,rda-method.Rd",
		"mda-class.Rd",
#			"initialize,mda-method.Rd",
		"loclda-class.Rd",
#			"initialize,loclda-method.Rd",
		"rpart.classif-class.Rd",
#			"initialize,rpart.classif-method.Rd",
		"randomForest.classif-class.Rd",
#			"initialize,randomForest.classif-method.Rd",
		"adaboost-class.Rd",
#			"initialize,adaboost-method.Rd",
		"kernlab.svm.classif-class.Rd",
#			"initialize,kernlab.svm.classif-method.Rd",
#			"train.learner,kernlab.svm.classif,formula,data.frame,numeric,list-method.Rd",
		
		"blackboost.regr-class.Rd",
#			"initialize,blackboost.regr-method.Rd",
		"gbm.regr-class.Rd",
#			"initialize,gbm.regr-method.Rd",
		"kknn.regr-class.Rd",
#			"initialize,kknn.regr-method.Rd",
		"penalized.lasso-class.Rd",
#			"initialize,penalized.lasso-method.Rd",
#			"train.learner,penalized.lasso,formula,data.frame,numeric,list-method.Rd",
		"stats.lm-class.Rd",
#			"initialize,stats.lm-method.Rd",
		"penalized.ridge-class.Rd"
#			"initialize,penalized.ridge-method.Rd",
#			"train.learner,penalized.ridge,formula,data.frame,numeric,list-method.Rd"
)		

	