allowed.rd.files <<- c( 		
		"undocumented.Rd",
		"logger.setup.Rd",
		"errorhandler.setup.Rd",
		"parallel.setup.Rd",
		"object-class.Rd",
		"to.string.Rd",

		"task.desc-class.Rd",
    "LearnTask-class.Rd",
    "ClassifTask-class.Rd",
		"RegrTask-class.Rd",
    "prepare.control.Rd",
		"makeClassifTask.Rd",
    "makeRegrTask.Rd",
    "subset.Rd",
    "get.data.Rd",
    "getFeatureNames.Rd",
    
		"trainLearner.Rd",
		"predictLearner.Rd",
		"args.to.control.Rd",
		
		"par.desc-class.Rd",
    "is.feasible.Rd",
    "Learner-class.Rd",
		"rlearner-class.Rd",
		"rlearner.classif-class.Rd",
		"rlearner.regr-class.Rd",
		"makeLearner.Rd",
		"setHyperPars.Rd",
		"setId.Rd",
    "setPredictType.Rd",
    "learners.Rd",
		"getLearners.Rd",
		
		"train.Rd",
		"WrappedModel-class.Rd",
		"predict.Rd",
		"Prediction-class.Rd",
    "setThreshold.Rd",
    
		"performance.Rd",
		"conf.matrix.Rd",
		"aggregations.Rd",
    "Measure-class.Rd",
    "makeMeasure.Rd",
    "makeCostMeasure.Rd",
    "measures.Rd",
		"losses.Rd",
		
		"ROCR_performance.Rd",
		"ROCR_performance-class.Rd",
		"ROCR_prediction.Rd",
		"ROCR_prediction-class.Rd",
		"ROCR_plot-methods.Rd",
    "ROCR.plot.task.Rd",
    #		"ROCR_simple.Rd",
#		"ROCR_xval.Rd",
		
		"makeResampleInstance.Rd",
		"makeResampleDesc.Rd",
		"ResampleDesc-class.Rd",
		"ResampleInstance-class.Rd",
		"resample.update.Rd",
		"resample.done.Rd",
		"resample.Rd",
		"ResamplePrediction-class.Rd",
		"as.ROCR.preds.Rd",
    "iters.Rd",
    
#		"set.train.par.Rd",
#		"set.predict.par.Rd",
#

		"BaseWrapper-class.Rd",
		"OptWrapper-class.Rd",
    "makeTuneWrapper.Rd",
    "makeVarselWrapper.Rd",
    #		"PreprocWrapper-class.Rd",
		"makePreprocWrapper.Rd",
		"makeMulticlassWrapper.Rd",
    "MulticlassWrapper-class.Rd",
    "makeProbthWrapper.Rd",
    "ProbthWrapper-class.Rd",
    "makeFilterWrapper.Rd",
		"FilterWrapper-class.Rd",
		
		"opt.control-class.Rd",
		"opt.result-class.Rd",
		
		"tune.Rd",
		"tune.threshold.Rd",
		"tune.control-class.Rd",
		"grid.control.Rd",
#		"ps.control.Rd",
		"optim.control.Rd",
		"cmaes.control.Rd",
		
		"varsel.control-class.Rd",
		"sequential.control.Rd",
		"randomvarsel.control.Rd",
		"varsel.Rd",
    "varfilter.Rd",
		
		
		"bench.exp.Rd",
		"bench.result-class.Rd"
		
)		

	