allowed.rd.files <<- c(     
  "undocumented.Rd",
  "setupLogger.Rd",
  "setupErrorHandler.Rd",
  "setupParallel.Rd",
  
  "TaskDesc-class.Rd",
  "LearnTask-class.Rd",
  "ClassifTask-class.Rd",
  "RegrTask-class.Rd",
  "makeClassifTask.Rd",
  "makeRegrTask.Rd",
  "subsetData.Rd",
  "getFormula.Rd",
  "getData.Rd",
  "getTargets.Rd",
  "getFeatureNames.Rd",
  
  "trainLearner.Rd",
  "predictLearner.Rd",
  "learnerArgsToControl.Rd",
  
  "Learner-class.Rd",
  "rlearner-class.Rd",
  "rlearner.classif-class.Rd",
  "rlearner.regr-class.Rd",
  "makeLearner.Rd",
  "getProperty.Rd",
  "setProperty.Rd",
  "setProperties.Rd",
  "getParamSet.Rd",
  "getHyperPars.Rd",
  "setHyperPars.Rd",
  "setId.Rd",
  "setPredictType.Rd",
  "learners.Rd",
  "getLearners.Rd",
  
  "train.Rd",
  "WrappedModel-class.Rd",
  "makeWrappedModel.Rd",
  "predict.Rd",
  "Prediction-class.Rd",
  "getProb.Rd",
  "setThreshold.Rd",
  
  "performance.Rd",
  "getConfMatrix.Rd",
  "Aggregation-class.Rd",
  "aggregations.Rd",
  "Measure-class.Rd",
  "setAggregation.Rd",
  "makeMeasure.Rd",
  "measures.Rd",
  "makeCustomResampledMeasure.Rd",
  
  "as.ROCR.prediction.Rd",
  "ROCR_performance.Rd",
  "ROCR_performance-class.Rd",
  "ROCR_prediction.Rd",
  "ROCR_prediction-class.Rd",
  "ROCR_plot-methods.Rd",
  "ROCR.plot.task.Rd",
#  "ROCR_simple.Rd",
#  "ROCR_xval.Rd",
  
  "makeResampleInstance.Rd",
  "makeResampleDesc.Rd",
  "ResampleDesc-class.Rd",
  "ResampleInstance-class.Rd",
#  "resample.update.Rd",
  "resample.done.Rd",
  "resample.Rd",
  "ResamplePrediction-class.Rd",
  "iters.Rd",
  
  "BaseWrapper-class.Rd"
)   

