allowed.rd.files <<- c( 		
		"undocumented.Rd",
		"logger.setup.Rd",
		"errorhandler.setup.Rd",
		"parallel.setup.Rd",
		"object-class.Rd",
		"to.string.Rd",

		"task.desc-class.Rd",
    "LearnTask-class.Rd",
    "ClassifTask-class.Rd",
		"RegrTask-class.Rd",
    "prepare.control.Rd",
		"makeClassifTask.Rd",
    "makeRegrTask.Rd",
    "subset.Rd",
    "get.data.Rd",
    
		"train.learner.Rd",
		"pred.learner.Rd",
		"args.to.control.Rd",
		
		"par.desc-class.Rd",
    "is.feasible.Rd",
    "learner-class.Rd",
		"rlearner-class.Rd",
		"rlearner.classif-class.Rd",
		"rlearner.regr-class.Rd",
		"makeLearner.Rd",
		"setHyperPars.Rd",
		"setId.Rd",
    "setPredictType.Rd",
    "learners.Rd",
		"get.learners.Rd",
		
		"train.Rd",
		"wrapped.model-class.Rd",
		"predict.Rd",
		"prediction-class.Rd",
    "set.threshold.Rd",
    
		"performance.Rd",
		"conf.matrix.Rd",
		"aggregations.Rd",
    "measure-class.Rd",
    "make.measure.Rd",
    "make.cost.measure.Rd",
    "measures.Rd",
		"losses.Rd",
		
		"ROCR_performance.Rd",
		"ROCR_performance-class.Rd",
		"ROCR_prediction.Rd",
		"ROCR_prediction-class.Rd",
		"ROCR_plot-methods.Rd",
    "ROCR.plot.task.Rd",
    #		"ROCR_simple.Rd",
#		"ROCR_xval.Rd",
		
		"make.res.instance.Rd",
		"make.res.desc.Rd",
		"resample.desc-class.Rd",
		"resample.instance-class.Rd",
		"resample.update.Rd",
		"resample.done.Rd",
		"resample.Rd",
		"resample.prediction-class.Rd",
		"as.ROCR.preds.Rd",
		
#		"set.train.par.Rd",
#		"set.predict.par.Rd",
#

		"base.wrapper-class.Rd",
		"opt.wrapper-class.Rd",
#		"preproc.wrapper-class.Rd",
		"make.preproc.wrapper.Rd",
		"make.multiclass.wrapper.Rd",
    "multiclass.wrapper-class.Rd",
    "make.probth.wrapper.Rd",
    "probth.wrapper-class.Rd",
    "make.filter.wrapper.Rd",
		"filter.wrapper-class.Rd",
		
		"opt.control-class.Rd",
		"opt.result-class.Rd",
		
		"tune.Rd",
		"tune.threshold.Rd",
		"tune.control-class.Rd",
		"grid.control.Rd",
#		"ps.control.Rd",
		"optim.control.Rd",
		"cmaes.control.Rd",
		"make.tune.wrapper.Rd",
		
		"varsel.control-class.Rd",
		"sequential.control.Rd",
		"randomvarsel.control.Rd",
		"varsel.Rd",
    "varfilter.Rd",
    "makeVarselWrapper.Rd",
		
		
		"bench.exp.Rd",
		"bench.result-class.Rd"
		
)		

	