allowed.rd.files <<- c( 		
		"undocumented.Rd",
		"logger.setup.Rd",
		"errorhandler.setup.Rd",
		"parallel.setup.Rd",
		"object-class.Rd",
		"to.string.Rd",

    "Parameter-class.Rd",
    "isFeasible.Rd",
    "makeNumericParameter.Rd",
    "makeNumericVectorParameter.Rd",
    "makeIntegerParameter.Rd",
    "makeIntegerVectorParameter.Rd",
    "makeDiscreteParameter.Rd",
    "makeLogicalParameter.Rd",
    "makeFunctionParameter.Rd",
    "makeUntypedParameter.Rd",
    "ParameterSet-class.Rd",
    "makeParameterSet.Rd",
    "lower.Rd",
    "upper.Rd",
    "values.Rd",
    
    "task.desc-class.Rd",
    "LearnTask-class.Rd",
    "ClassifTask-class.Rd",
		"RegrTask-class.Rd",
    "prepare.control.Rd",
		"makeClassifTask.Rd",
    "makeRegrTask.Rd",
    "subset.Rd",
    "get.data.Rd",
    "getTargets.Rd",
    "getFeatureNames.Rd",
    "getClassLevels.Rd",
    
		"trainLearner.Rd",
		"predictLearner.Rd",
		"args.to.control.Rd",
    
    "LearnerParameter-class.Rd",
    "makeNumericLearnerParameter.Rd",
    "makeNumericVectorLearnerParameter.Rd",
    "makeIntegerLearnerParameter.Rd",
    "makeIntegerVectorLearnerParameter.Rd",
    "makeDiscreteLearnerParameter.Rd",
    "makeLogicalLearnerParameter.Rd",
    "makeFunctionLearnerParameter.Rd",
    "Learner-class.Rd",
		"rlearner-class.Rd",
		"rlearner.classif-class.Rd",
		"rlearner.regr-class.Rd",
		"makeLearner.Rd",
    "getParameterSet.Rd",
    "getParameterValues.Rd",
    "setHyperPars.Rd",
		"setId.Rd",
    "setPredictType.Rd",
    "learners.Rd",
		"getLearners.Rd",
		
		"train.Rd",
		"WrappedModel-class.Rd",
		"predict.Rd",
		"Prediction-class.Rd",
    "getScore.Rd",
    "setThreshold.Rd",
    
		"performance.Rd",
		"getConfMatrix.Rd",
    "Aggregation-class.Rd",
    "aggregations.Rd",
    "Measure-class.Rd",
    "setAggregation.Rd",
    "makeMeasure.Rd",
    "measures.Rd",
		"losses.Rd",
		
		"ROCR_performance.Rd",
		"ROCR_performance-class.Rd",
		"ROCR_prediction.Rd",
		"ROCR_prediction-class.Rd",
		"ROCR_plot-methods.Rd",
    "ROCR.plot.task.Rd",
    #		"ROCR_simple.Rd",
#		"ROCR_xval.Rd",
		
		"makeResampleInstance.Rd",
		"makeResampleDesc.Rd",
		"ResampleDesc-class.Rd",
		"ResampleInstance-class.Rd",
		"resample.update.Rd",
		"resample.done.Rd",
		"resample.Rd",
		"ResamplePrediction-class.Rd",
		"as.ROCR.preds.Rd",
    "iters.Rd",
    
		"BaseWrapper-class.Rd",
		"makePreprocWrapper.Rd",
		"makeMulticlassWrapper.Rd",
    "MulticlassWrapper-class.Rd",
    "makeProbthWrapper.Rd",
    "ProbthWrapper-class.Rd"
)		

	