allowed.rd.files <<- c(     
  "undocumented.Rd",
  "logger.setup.Rd",
  "errorhandler.setup.Rd",
  "parallel.setup.Rd",
  "object-class.Rd",
  "to.string.Rd",
  
  "Parameter-class.Rd",
  "isFeasible.Rd",
  "makeNumericParameter.Rd",
  "makeNumericVectorParameter.Rd",
  "makeIntegerParameter.Rd",
  "makeIntegerVectorParameter.Rd",
  "makeDiscreteParameter.Rd",
  "makeLogicalParameter.Rd",
  "makeFunctionParameter.Rd",
  "makeUntypedParameter.Rd",
  "ParameterSet-class.Rd",
  "makeParameterSet.Rd",
  "lower.Rd",
  "upper.Rd",
  "values.Rd",
  
  "task.desc-class.Rd",
  "LearnTask-class.Rd",
  "ClassifTask-class.Rd",
  "RegrTask-class.Rd",
  "makeClassifTask.Rd",
  "makeRegrTask.Rd",
  "subset.Rd",
  "getData.Rd",
  "getTargets.Rd",
  "getFeatureNames.Rd",
  "getClassLevels.Rd",
  
  "trainLearner.Rd",
  "predictLearner.Rd",
  "args.to.control.Rd",
  
  "LearnerParameter-class.Rd",
  "makeNumericLearnerParameter.Rd",
  "makeNumericVectorLearnerParameter.Rd",
  "makeIntegerLearnerParameter.Rd",
  "makeIntegerVectorLearnerParameter.Rd",
  "makeDiscreteLearnerParameter.Rd",
  "makeLogicalLearnerParameter.Rd",
  "makeFunctionLearnerParameter.Rd",
  "makeUntypedLearnerParameter.Rd",
  "Learner-class.Rd",
  "rlearner-class.Rd",
  "rlearner.classif-class.Rd",
  "rlearner.regr-class.Rd",
  "makeLearner.Rd",
  "getProperty.Rd",
  "setProperty.Rd",
  "setProperties.Rd",
  "getParameterSet.Rd",
  "getParameterValues.Rd",
  "setHyperPars.Rd",
  "setId.Rd",
  "setPredictType.Rd",
  "learners.Rd",
  "getLearners.Rd",
  
  "train.Rd",
  "WrappedModel-class.Rd",
  "predict.Rd",
  "Prediction-class.Rd",
  "getScore.Rd",
  "setThreshold.Rd",
  
  "performance.Rd",
  "getConfMatrix.Rd",
  "Aggregation-class.Rd",
  "aggregations.Rd",
  "Measure-class.Rd",
  "setAggregation.Rd",
  "makeMeasure.Rd",
  "measures.Rd",
  "losses.Rd",
  
  "as.ROCR.prediction.Rd",
  "ROCR_performance.Rd",
  "ROCR_performance-class.Rd",
  "ROCR_prediction.Rd",
  "ROCR_prediction-class.Rd",
  "ROCR_plot-methods.Rd",
  "ROCR.plot.task.Rd",
  #   "ROCR_simple.Rd",
#   "ROCR_xval.Rd",
  
  "makeResampleInstance.Rd",
  "makeResampleDesc.Rd",
  "ResampleDesc-class.Rd",
  "ResampleInstance-class.Rd",
  "resample.update.Rd",
  "resample.done.Rd",
  "resample.Rd",
  "ResamplePrediction-class.Rd",
  "iters.Rd",
  
  "BaseWrapper-class.Rd"
)   

