#' @include resample.instance.r
#' @include bs.desc.r
roxygen()


#' A bs.instance object is mainly a set of integer vectors generated by bootstrapping. 
#' They indicate the training part of data for different instances of bs.
#'
#' @note Normally you don't want to use the S4 constructor, but instead \code{\link{make.bs.instance}}.
#' 
#' @title bs.instance
#' @exportClass bs.instance

setClass(
		"bs.instance", 
		contains = c("resample.instance"))                                                     

#' Constructor.
#' @title bs.instance constructor
#' @rdname bs.instance-class

setMethod(
  f = "initialize",
  signature = signature("bs.instance"),
  def = function(.Object, desc, size) {
	inds <- boot(1:size, R=desc["iters"], function(data,inds) inds)$t
	inds <- as.list(as.data.frame(t(inds)))
	names(inds) <- NULL
	
	callNextMethod(.Object, desc=desc, size=size, inds=inds)
  }
)


setGeneric(
		name = "make.bs.instance",
		def = function(size, iters) {
			standardGeneric("make.bs.instance")
		}
)

#' \code{make.bs.instance} generates a \code{\linkS4class{bs.instance}} object, which encapsulates the generated indices of training and test sets. 
#' 
#' @param size [integer] \cr Size of the data set to resample. 
#' @param iters [integer] \cr Number of generated subsets / resampling iterations.
#' 
#' @return A \code{\linkS4class{bs.instance}} object, which encapsulates the generated indices of training and test sets.
#' 
#' @export
#' @rdname make.bs.instance 
#' 
#' @usage make.bs.instance(size, iters)
#' 
#' @examples 
#' data(iris)
#' rin <- make.bs.instance(size=nrow(iris), iters=10)
#' 
#' @seealso \code{\link{resample.fit}}, \code{\linkS4class{bs.instance}}
#' 
#' @title make.bs.instance


setMethod(
		f = "make.bs.instance",
		signature = signature(size="numeric", iters="numeric"),
		def = function(size, iters) {
			desc <- new("bs.desc", iters=iters)
			return(new("bs.instance", desc=desc, size=size))
		}
)

