#' @include resample.instance.r
#' @include bs.desc.r
roxygen()

#'  \describe{	
#' A bs.instance object is mainly a set of integer vectors generated by bootstrapping. 
#' They indicate the training part of data for different instances of bs.} 
#'
#' 
#' \cr\cr\bold{Slots:}
#'  \describe{	
#'   \item{\code{size [numeric]}}{Number of observations in the data which will be used for training the model}
#'   \item{\code{inds [matrix]}}{Matrix of index vectors specifying the cases of the training sample for each bootstrap instance.}
#'  }
#' 
#'  @note  
#'  The slot \code{inds} is generated automaticly if the optional argument \code{iters}
#'  is used. In this case \code{inds} consists of iters integer vectors drawn from 1:size using bootstrapping.
#' 
#'  @title bs.instance
#' @export


setClass("bs.instance", contains="resample.instance")                                                     

setMethod(
  f = "initialize",
  signature = "bs.instance",
  def = function(.Object, desc, size) {
	inds <- boot(1:size, R=desc["iters"], function(data,inds) inds)$t
	inds <- as.list(as.data.frame(t(inds)))
	names(inds) <- NULL
	
	callNextMethod(.Object, desc=desc, size=size, inds=inds)
  }
)

setGeneric(
		name = "make.bs.instance",
		def = function(size, iters) {
			standardGeneric("make.bs.instance")
		}
)

#' make.bs.instance generates training and test set indices for bootstrapping. 
#' 
#' @param size [integer] \cr Size of the data set to resample. 
#' @param iters [integer] \cr Number of generated subsets / resampling iterations.
#' 
#' @return A \code{\linkS4class{bs.instance}} object, which encapsulates the generated indices of training and test sets.
#' 
#' @export
#' 
#' @examples 
#' data(iris)
#' rin <- make.bs.instance(iters=10, size=nrow(iris))
#' 
#' @seealso \code{\link{resample.fit}}
#' 
#' @title make.bs.instance


setMethod(
		f = "make.bs.instance",
		signature = c(size="numeric", iters="numeric"),
		def = function(size, iters) {
			desc <- new("bs.desc", iters=iters)
			return(new("bs.instance", desc=desc, size=size))
		}
)

