#' @include resample.instance.r
#' @include subsample.desc.r
roxygen()

#' A subsample.instance object is mainly a set of integer vectors generated by subsampling. 
#' They indicate the training part of data for different instances of subsample.
#'
#' @note Normally you don't want to use the S4 constructor, but instead \code{\link{make.subsample.instance}}.
#' 
#' @title subsample.instance
#' @exportClass subsample.instance

setClass(
		"subsample.instance", 
		contains = c("resample.instance")
)                                                     


#' Constructor.
#' @title subsample.instance constructor
#' @rdname subsample.instance-class

setMethod(
		f = "initialize",
		signature = signature("subsample.instance"),
		def = function(.Object, desc, size) {
			inds <- lapply(1:desc["iters"], function(x) sample(1:size, size*desc["split"]))
			callNextMethod(.Object, desc=desc, size=size, inds=inds)
		}
)


setGeneric(
		name = "make.subsample.instance",
		def = function(size, split, iters) {
			if (missing(split))
				split = 2/3
			if (missing(iters))
				iters = 1
			standardGeneric("make.subsample.instance")
		}
)

#' \code{make.subsample.instance} generates a \code{\linkS4class{subsample.instance}} object, which encapsulates the generated indices of training and test sets. 
#' 
#' @param size [integer] \cr Size of the data set to resample.
#' @param split [numeric] \cr Proportion of data used for training set. 
#' @param iters [integer] \cr Number of generated subsets / resampling iterations.
#' 
#' @return A \code{\linkS4class{subsample.instance}} object, which encapsulates the generated indices of training and test sets.
#' 
#' @export
#' @rdname make.subsample.instance 
#' 
#' @usage make.subsample.instance(size, split, iters)
#' 
#' @examples 
#' data(iris)
#' # split is the training set percentage
#' rin <- make.subsample.instance(size=nrow(iris), split=2/3, iters=10)
#' # holdout
#' rin <- make.subsample.instance(size=nrow(iris), split=2/3, iters=1)
#' 
#' @seealso \code{\link{resample.fit}}, \code{\linkS4class{subsample.instance}}
#' 
#' @title make.subsample.instance


setMethod(
		f = "make.subsample.instance",
		signature = c(size="numeric", split="numeric", iters="numeric"),
		def = function(size, split, iters) {
			desc <- new("subsample.desc", iters=iters, split=split)
			return(new("subsample.instance", desc=desc, size=size))
		}
)
