#' @include task.learn.r
roxygen()

#---------------- class model --------------------------------------------

#' A classifier model is generated by \code{\link{train}}. It consists of the learn.task,
#' the classification model, the used hyperparameters and a vector specifying the cases of the training sample. 
#' 
#' @slot task.class [\code{\link{learn.task}}] Specifies learning task
#' @slot learner.class [\code{\link{character}}] Specifies learner class
#' @slot learner.name [\code{\link{character}}] Name of the learning method
#' @slot learner.model [external.model] External model from existing R packages like lda, rpart, etc
#' @slot subset [\code{\link{integer}}] An index vector specifying the cases of the training sample that were used for the model. 
#' @slot vars [\code{\link{charactter}}] Vector specifying the variables which were used to build the model. 
#' @slot parset [\code{\link{list}}] Contains the hyperparameters of the train function. If empty no parameters were used.
#' 
#' @examples  see \link{train}
#' 
#' @title wrapped.model
#' @importFrom stats predict
 
setClass(
		"wrapped.model",
		representation = representation(
				task.class = "character",
				learner.class = "character",
				learner.name = "character",
				learner.model = "ANY",
				subset = "numeric",
				vars = "character",
				parset = "list"
		)
)

setClass(
		"wrapped.classif.model",
		contains = c("wrapped.model")
)

setClass(
		"wrapped.regr.model",
		contains = c("wrapped.model")
)



#---------------- predict --------------------------------------------



#' Conversion to string.
setMethod(
		f = "as.character",
		signature = signature("wrapped.model"),
		def = function(x) {
			ps <- paste(names(x@parset), x@parset, sep="=", collapse=" ")
			return(
					paste(
							"Learner model for ", x@learner.name, "\n",  
							"Hyperparameters: ", ps, "\n",
							"Trained on obs: ", length(x@subset), "\n",
							sep=""
					)
			)
		}
)

#' Prints the object by calling as.character.
setMethod(
		f = "print",
		signature = signature("wrapped.model"),
		def = function(x, ...) {
			cat(as.character(x))
		}
)

#' Shows the object by calling as.character.
setMethod(
		f = "show",
		signature = signature("wrapped.model"),
		def = function(object) {
			cat(as.character(object))
		}
)


#' Getter.
#' @param x wrapped.model object
#' @param i [\code{\link{character}}]
#' \describe{
#'   \item{learn.task}{The learning task.}
#'   \item{subset}{An index vector specifying the cases of the training sample that were used for the model.}
#'   \item{parset}{Contains the hyperparameters of the train function.}
#'   \item{learner.model}{External model from existing R packages like lda, rpart, etc.}
#' }
#' 
#' @rdname getter,wrapped.model-method
#' @aliases wrapped.model-getter 
#' @title Getter for wrapped.model

setMethod(
		f = "[",
		signature = signature("wrapped.model"),
		def = function(x,i,j,...,drop) {
			if (i == "learn.task"){
				return(x@learn.task)
			}
			if (i == "subset"){
				return(x@subset)
			}
			if (i == "parset"){
				return(x@parset)
			}
			if (i == "learner.model"){
				return(x@learner.model)
			}
			
			y <- x@learn.task[i,j,...,drop]
			return(y)
		}
)











